name:DelayTheInevitable

on:
  push:
    branches:
      - main

env:
  itchio_project: jessefreeman/delay-the-inevitable

jobs:

  # This runs before the builds and creates the new feature release
  create-release:

    name: "Create Release"
    runs-on: "ubuntu-latest"

    # Steps for the task
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow
      
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Build
        run: |
          npm install
          npm install gulp -g
          gulp
          
      - name: Upload project
        uses: robpc/itchio-upload-action@v1
        with:
          path: Releases/DelayTheInevitable.zip
          project: ${{ env.itchio_project }}
          channel: files
          api-key: ${{ secrets.ITCHIO_API_KEY }}